name: Deploy application to beanstalk
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName

      - name: Generate deployment package
        run: zip -r deploy.zip . docker-compose.yml

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: pfswcho_app
          environment_name: pfswcho-app-dev
          version_label: ${{ steps.tagName.outputs.tag }}
          region: eu-west-1
          deployment_package: deploy.zip